name: Pull request dev

on:
  pull_request:
    branches:
      - dev

jobs:
  Test:
    runs-on: ubuntu-latest
    strategy:
      # You can use PyPy versions in python-version.
      # For example, pypy2 and pypy3
      matrix:
        python-version: [3.7, 3.8, 3.9]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      # You can test your matrix by printing the current Python version
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest pytest-cov
          pip install -e .
          pip install -r requirements.txt
      - name: Lint with flake8
        run: |
          flake8 ./label_chess/* --max-line-length=90 --exclude=tests/*,label_chess/VERSION,label_chess/__init__.py
      - name: Test with pytest
        run: |
          pytest -vvv tests/* --cov=label_chess